# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20160830_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(max_length=5)),
                ('mobile_phone', models.CharField(default='', max_length=20)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('home_phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('passport', models.CharField(default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('joined', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['last_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('postal_code', models.CharField(max_length=5)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['postal_code', 'name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['field', 'name'], 'verbose_name_plural': 'Specialities'},
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.City'),
        ),
        migrations.AddField(
            model_name='university',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Province'),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.City'),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Country'),
        ),
        migrations.AddField(
            model_name='member',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Province'),
        ),
    ]
